services:
- docker
env:
  global:
  - AUTHOR_EMAIL=gambol99@gmail.com
  - REGISTRY_USERNAME=ukhomeofficedigital+vault_sidekick
  - REGISTRY=quay.io
  - secure: bX5gbuMoAC5RIY+68+s2zQ2nN9ItKN2cctVXABa6foCommV/ED8CcscPgWyyojq5KLlzcV+3wi8d2ZKDwnzePgv2HkJJSup15WHxiZhxNQwnHnObHSnNRPTQcUj0sjyHZX22JhS2M6vifia/5uK2yhVNKDdBJBfPey600xfC50ElQG8elOe/YeJCiqg/bVv/BT1Ejq2mo6ARtrXiQ5YgXnei7wXanv72nS2aYq9QZRIw4/8lydEQsPeTSIf+VncaaTfh6Kw0JHERHM672uexg8HXRwDI/o/Q6DI54Lf0uWmFF2rS+DAJLcXNDKKzf+axxN2IoAu2EmEgq7VqHX1CPEKEWtoJf+cYDV4zpWElHIsE6aK4Ycvn3uy3Vf8SfJ45kR2/bmlqh0HN24Ivdqd0joO8WoZ8KlmJ9zFF3DvnOVOhctLXH1ypeQl3s3G3AH3WfDpJyTR8qTNlfScaE6PEwo4I41GfwE0zMnugur+DTBHoLWOLIqlm48Jxh6k8TUWY5JvvPvIMNJYRo48zSCPu7x3hNYaoAsBAWEdlITCM7q+R48uRLdWCklN9LcTfzJWOATo+R9BQib52ZCREr2Bl9qYJ2nokhtAGccO3re9BboMM68PRJMCNWEW9bj+iQBl4W7/Mzp7j7cAHkq+iNheH/BYA2qVJIriPwfncExR7hok=
  - secure: "KmhRHvkuNKxgKbrVMGrYAurPOVlFuySu/JLiiVPbNUuVyicNM2foijOCjBCXdWyOwnwKNvLUsOXw445PxuiChsVmz9i/dTPipQwd4UNs17dNHaosc2OaUwK2HiFbqBPrXFxZcavnCqTm1a17wA3KlWuwhhPVinDb7rrJWLmLlvKgthvqZQPEpfeDE5kO2IIeal5+fQxhd1cAp2l2lHXUGhF5tdkvyOcQocN84y4BU/Sq9MpMhf5VwJN+lAW7R2gZeKm9UNHDxCAZoBsk8UY+LVrxBDbbNBpiDTJBUqshidfJJ8JhcQ3IGCS9p8Qm2oS7kzIFAoNLJrvp1Gyxshj4m5wgquv/xANG48p82ChGcuMl3RLMNKR4BkIVC5MTBvPrNIfDb7N1QIS3GR4cLjDz8FygbyvKIEGiCQ+WyAAhMpgcYYgcBGL1ZBxl7wHIvfDYbbhTXd2zT9YxdBcds0hRo4rxg26teaQAtlIeQl57lZT6uPKEmwVsCjEFwV9FcILjZeGuCJrGns/Rq61kQ75ug10xgkxVlJnry5Ihh++CEYRfMaL7nae7smhpmfrAZLD/cL6z9Ozs4cb9zouBZSQOLVKjCLQU+M9L73qneMO24cwnf2uQKaILrFVhlP5ZIkr/7g3vcl2K3YUoVgYUL7Umxeh03oz2VPUiTd6c7vPjRcE="
language: go
go: 1.9.3
install: true
script:
- make test
- if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_EVENT_TYPE} == "push" ]]) || [[ -n ${TRAVIS_TAG} ]]; then
    GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.gitsha=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/vault-sidekick_linux_amd64;
    GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.gitsha=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/vault-sidekick_darwin_amd64;
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.gitsha=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}d}" -o bin/vault-sidekick_windows_amd64.exe;
    docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} ${REGISTRY};
    VERSION=${TRAVIS_TAG:-latest} make docker-release;
  fi
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: UKHomeOffice/vault-sidekick
  #  tags: true
  api_key:
    secure: "${GITHUB_TOKEN}"
  file:
  - bin/vault-sidekick_linux_amd64
  - bin/vault-sidekick_darwin_amd64
  - bin/vault-sidekick_windows_amd64.exe
