services:
- docker
env:
  global:
  - AUTHOR_EMAIL=gambol99@gmail.com
  - REGISTRY_USERNAME=ukhomeofficedigital+vault_sidekick
  - REGISTRY=quay.io
  - secure: bX5gbuMoAC5RIY+68+s2zQ2nN9ItKN2cctVXABa6foCommV/ED8CcscPgWyyojq5KLlzcV+3wi8d2ZKDwnzePgv2HkJJSup15WHxiZhxNQwnHnObHSnNRPTQcUj0sjyHZX22JhS2M6vifia/5uK2yhVNKDdBJBfPey600xfC50ElQG8elOe/YeJCiqg/bVv/BT1Ejq2mo6ARtrXiQ5YgXnei7wXanv72nS2aYq9QZRIw4/8lydEQsPeTSIf+VncaaTfh6Kw0JHERHM672uexg8HXRwDI/o/Q6DI54Lf0uWmFF2rS+DAJLcXNDKKzf+axxN2IoAu2EmEgq7VqHX1CPEKEWtoJf+cYDV4zpWElHIsE6aK4Ycvn3uy3Vf8SfJ45kR2/bmlqh0HN24Ivdqd0joO8WoZ8KlmJ9zFF3DvnOVOhctLXH1ypeQl3s3G3AH3WfDpJyTR8qTNlfScaE6PEwo4I41GfwE0zMnugur+DTBHoLWOLIqlm48Jxh6k8TUWY5JvvPvIMNJYRo48zSCPu7x3hNYaoAsBAWEdlITCM7q+R48uRLdWCklN9LcTfzJWOATo+R9BQib52ZCREr2Bl9qYJ2nokhtAGccO3re9BboMM68PRJMCNWEW9bj+iQBl4W7/Mzp7j7cAHkq+iNheH/BYA2qVJIriPwfncExR7hok=
#  - secure: WM45k/RsJi7SqMuF8OSRk6Zhk/QnhiVwOtoBKsmRqsPYkzo87k0ZB/abV87+qfdwtj1dPtG9ByzHJCxWJgXvNBLq03v5rxhhU1xB0fhBTps+6uUCjB3k/DR7qEXHNU1kj5273UxpJJozyx6pCuEfAr5H6sBB9pU7DOV57Gr2XbaLBvwX1rHsgeeQqJkP70v5VjPmxDYPjSRo20qSZ9iPNt+m+jb6raowk4elXl45BQ6j2IiDeFjJ+/THyf9YfLnId0ibi+s56rBr/IxF3fir6t5N2pRn3oM/TUwDnpkv4pdpjOtepxN4RZPk3SfTK25T1idTZMGs+2cCRzHlGQRZfKgF1ml4otVs3t7eM64OdIc06S8rJU3WpZxG52kMMN6OXrVHPproB4nuRxcdW7iNnHgn6ymmTyjfyj9XYOFBL/1lj/1YIkiGt5u0tm62rWXT9Yh3i3iq8zObDnEZtS9W4nlyD0e82+TeiH0tnEaIKbkS1XRKfdg7dMSozqlVvFxSFlVp07w+mNKpUoqEGXwtelrTdNPN2fp2LLypVSnhhUVmF4E+l6YGaRYPovnX/L9EN8CtgJ/G8/I4TQ1qkky+6ON3ENbb0wMkVktlw/CARZneT46jzgeFzlmOIaDE+jTQT8aTBgA54FEXH0B4Xs+llgBQAR5/azoRYyV+VOHomvE=
secure: "RkA1KKUuRFAhAaGUuSOLeq+YPNrIjrZBz7b5T3/dqxfhlxAytt0bgiyn83sV76qrMEmak623tB5UMHHDB/up3XrDyKlkjj6du+44j1JUcFuZZEnckAaTK7YJWPm3TsBrG/P4i6bygq19FRHdxt/z0tdtdO5SfW19le7CGEZcHg+/4NxGY0/1wQfUxrJm9IPGgtJhB7hIPPqH17b0/kbt+pPGHF071z5fgYX6auE5afK5w/vus9XxLwZ8pxSWr96hdrrZ1uN7BXAhahaxc1N4xDWqYvWsxE8iIk2TZsJObV3cgsM8Z3Vrfndv/rYp33DOP4nbSL4WKpC2r3Il6PGT6+4WLE1wW6wHXnlVJFumki3J1dnDJnNEKmYf9SlpWGi9+tCsdyiA1STX1ZN5MbLbsGJGBdJFyqPPaiascKnSVwsq0J6RWsXX1szoF6zHmy+nMcPPu6kC13vUUSZebPg08PzjfLbspEh3dMfS+IrAjCBltUw/HAfQOLJaG/toXvEd1kHQyqgWGda1WWAs5tfN/noXkNBuXLP/D7pQOvo5tVOC/PEDUhJsWqxacZG63dLPNU0cZQ7AMJ/FOuGfu1oL46DFljEDiRi34Zzt8jDIttE4ts8vC1579nc9w1LYslR/PAU62767FSgI1gdqt3P1BMnV2NmCv+tzPmPxAor/11M="
language: go
go: 1.9.3
install: true
script:
- make test
- if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_EVENT_TYPE} == "push" ]]) || [[ -n ${TRAVIS_TAG} ]]; then
    GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.gitsha=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/vault-sidekick_linux_amd64;
    GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.gitsha=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}}" -o bin/vault-sidekick_darwin_amd64;
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X main.gitsha=${TRAVIS_TAG:-git+${TRAVIS_COMMIT}d}" -o bin/vault-sidekick_windows_amd64.exe;
    docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} ${REGISTRY};
    VERSION=${TRAVIS_TAG:-latest} make docker-release;
  fi
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: UKHomeOffice/vault-sidekick
    tags: true
  api_key:
    secure: "${GITHUB_TOKEN}"
  file:
  - bin/vault-sidekick_linux_amd64
  - bin/vault-sidekick_darwin_amd64
  - bin/vault-sidekick_windows_amd64.exe
